// Zues editor entry point. Phase 4.1: ImGui editor with dark theme + panels.
//
// Boots the engine, opens the GLFW window via the window module, initializes
// ImGui on top, runs a real game loop driving panels (Hierarchy / Inspector
// / Console / Scene placeholder).

#include "editor.h"
#include "editor_systems.h"
#include <zues/host/host_api.h>
#include <zues/host/host_context.h>
#include "native_dialog.h"
#include <zues/host/project_loader.h>
#include <zues/host/render_camera_service.h>
#include <zues/host/animator_system.h>
#include <zues/host/particle_system.h>
#include <zues/host/audio_system.h>
#include <zues/host/sprite_render_system.h>
#include <zues/host/ui_render_system.h>
#include "world_io.h"

#include <zues/asset.h>
#include <zues/components.h>
#include <zues/ecs.h>
#include <zues/engine.h>
#include <zues/events.h>
#include <zues/log.h>
#include <zues/project.h>
#include <zues/project_api.h>
#include <zues/service.h>
#include <zues/services/physics.h>
#include <zues/services/renderer_2d.h>
#include <zues/services/window.h>

#include <imgui.h>

#include <cmath>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <vector>

#if defined(_WIN32)
    #define WIN32_LEAN_AND_MEAN
    #include <windows.h>
#else
    #include <climits>
    #include <sys/wait.h>
    #include <unistd.h>
#endif

#include <GLFW/glfw3.h>

// ---- Demo / smoke component types — exposed at file scope so the macros
// can specialize the reflection traits. Kept from earlier phases.
struct Position   { float x, y; };
struct Velocity   { float vx, vy; };
struct Tag_Player {};
ZUES_COMPONENT_FIELDS(Position, x, y);
ZUES_COMPONENT_FIELDS(Velocity, vx, vy);
ZUES_COMPONENT_TAG   (Tag_Player);

struct WindowResized {
    static constexpr const char* EVENT_ID = "zues.window_resized";
    int width;
    int height;
};

namespace {

// ---- Lync auto-compile helpers ---------------------------------------------

// Auto-generated manifest filename. Lives in src/ so Lync's `include` (which
// resolves module names against the source file's directory) can find every
// other .lync file alongside it. Marked with a `_zues_` prefix so the
// Source pane can filter it out + so the user knows not to edit it.
inline const char* kZuesManifestName = "_zues_main.lync";

// (Re)generate the auto-include manifest. Scans `src_dir` for every *.lync
// (excluding the manifest itself, hidden `_zues_*` files, and `.__live.lync`
// temp files), then writes:
//
//   // AUTO-GENERATED - do not edit. Regenerated by the editor.
//   include FileA.*
//   include FileB.*
//   ...
//
// `include FileA.*` resolves to `<src_dir>/FileA.lync` because Lync's
// resolve_module_path uses the source file's directory as the base. Returns
// true if the manifest content actually changed (so the watcher can decide
// to recompile). No-op if `src_dir` doesn't exist.
bool regenerate_lync_manifest(const std::filesystem::path& src_dir,
                               const std::filesystem::path& manifest_path) {
    std::error_code ec;
    if (!std::filesystem::exists(src_dir, ec)) return false;

    std::vector<std::string> stems;
    for (const auto& e : std::filesystem::directory_iterator(src_dir, ec)) {
        if (!e.is_regular_file(ec)) continue;
        if (e.path().extension() != ".lync") continue;
        const std::string fn = Engine::editor::path_str(e.path().filename());
        if (fn == kZuesManifestName)              continue;
        if (fn.rfind("_zues_", 0) == 0)           continue;
        if (fn.find(".__live.") != std::string::npos) continue;
        stems.push_back(Engine::editor::path_str(e.path().stem()));
    }
    std::sort(stems.begin(), stems.end());

    std::string body;
    body += "// AUTO-GENERATED - do not edit.\n";
    for (const auto& s : stems) {
        body += "include ";
        body += s;
        body += ".*;\n";        // Lync's parser requires the trailing ';'
    }

    std::string prev;
    if (std::filesystem::exists(manifest_path, ec)) {
        std::ifstream in(manifest_path, std::ios::binary);
        std::ostringstream ss; ss << in.rdbuf();
        prev = ss.str();
    }
    if (prev == body) return false;

    std::ofstream out(manifest_path, std::ios::binary | std::ios::trunc);
    if (!out) return false;
    out.write(body.data(), (std::streamsize)body.size());
    return true;
}

// Walk project_dir recursively; return the maximum last-write-time across
// all .lync files. Returns a zero-initialised time_point if none are found.
std::filesystem::file_time_type scan_lync_mtime(const std::filesystem::path& dir) {
    std::filesystem::file_time_type max_t{};
    std::error_code ec;
    for (const auto& entry : std::filesystem::recursive_directory_iterator(
             dir, std::filesystem::directory_options::skip_permission_denied, ec)) {
        if (entry.path().extension() == ".lync") {
            const auto t = std::filesystem::last_write_time(entry.path(), ec);
            if (!ec && t > max_t) max_t = t;
        }
    }
    return max_t;
}

}  // namespace (anonymous)

namespace Engine::editor {

// Synchronously run cmd (shell syntax, stderr merged via "2>&1") and return
// the process exit code. Captured stdout+stderr are appended to `out`.
// Returns -1 if the process could not be spawned.
//
// On Windows we explicitly avoid `_popen`: it spawns through cmd.exe with no
// way to suppress the console window, so every invocation flashes a black
// rectangle on screen (very visible on file switch, save, etc.). Instead we
// use CreateProcess + CREATE_NO_WINDOW with an anonymous pipe for stdout.
//
// Declared in editor.h so panel_lync_editor.cpp can call it.
int run_capture(const std::string& cmd, std::string& out) {
    out.clear();
#if defined(_WIN32)
    // Pipe for child stdout (and stderr - we merge them).
    HANDLE rd = nullptr, wr = nullptr;
    SECURITY_ATTRIBUTES sa{};
    sa.nLength = sizeof(sa);
    sa.bInheritHandle = TRUE;
    if (!CreatePipe(&rd, &wr, &sa, 0)) return -1;
    // Read end of the pipe must NOT be inherited by the child, otherwise the
    // pipe stays open after the child exits and ReadFile blocks forever.
    SetHandleInformation(rd, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOA si{};
    si.cb         = sizeof(si);
    si.dwFlags    = STARTF_USESTDHANDLES;
    si.hStdOutput = wr;
    si.hStdError  = wr;
    si.hStdInput  = GetStdHandle(STD_INPUT_HANDLE);

    PROCESS_INFORMATION pi{};
    // CreateProcessA requires a writable command-line buffer.
    std::vector<char> cmdline(cmd.begin(), cmd.end());
    cmdline.push_back('\0');

    const BOOL ok = CreateProcessA(
        /*lpApplicationName*/ nullptr,
        /*lpCommandLine*/     cmdline.data(),
        /*lpProcessAttributes*/ nullptr,
        /*lpThreadAttributes*/  nullptr,
        /*bInheritHandles*/   TRUE,
        /*dwCreationFlags*/   CREATE_NO_WINDOW,
        /*lpEnvironment*/     nullptr,
        /*lpCurrentDirectory*/nullptr,
        &si, &pi);

    // Parent must close its copy of the write end so ReadFile sees EOF when
    // the child exits.
    CloseHandle(wr);
    if (!ok) {
        const DWORD err = GetLastError();
        char msg[256];
        std::snprintf(msg, sizeof(msg), "run_capture: CreateProcess failed (err=%lu): %s",
                      err, cmdline.data());
        log_write(LogLevel::Error, "editor", msg);
        CloseHandle(rd);
        return -1;
    }

    char buf[512];
    DWORD nread = 0;
    while (ReadFile(rd, buf, (DWORD)sizeof(buf), &nread, nullptr) && nread > 0) {
        out.append(buf, buf + nread);
    }
    CloseHandle(rd);

    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD code = 0;
    GetExitCodeProcess(pi.hProcess, &code);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    return (int)code;
#else
    FILE* f = ::popen(cmd.c_str(), "r");
    if (!f) return -1;
    char buf[512];
    while (std::fgets(buf, sizeof(buf), f)) out += buf;
    const int status = ::pclose(f);
    return WIFEXITED(status) ? WEXITSTATUS(status) : -1;
#endif
}

}  // namespace Engine::editor

namespace {

// Forward decl - implementation below.
std::filesystem::path executable_dir();

// When the project's build.lync_X is empty, fall back to a copy bundled
// next to editor.exe (under <exe_dir>/lync/). This makes packaged builds
// portable: a fresh project doesn't need to hardcode any C:/LyncLang/ path.
// Returns an empty string only when neither the project value nor the
// bundled fallback exists - caller decides what to do.
std::string lync_fallback(const std::string& from_project,
                           const std::filesystem::path& project_base,
                           const char* bundled_filename) {
    if (!from_project.empty()) {
        auto p = std::filesystem::path(from_project);
        return (p.is_absolute() ? p : project_base / p).string();
    }
    std::error_code ec;
    const auto bundled = executable_dir() / "lync" / bundled_filename;
    if (std::filesystem::exists(bundled, ec)) return bundled.string();
    return {};
}

// Build the lync compiler shell invocation from a project's build config.
// Returns an empty string if lync_main is not set.
std::string build_lync_cmd(const Engine::Project& proj) {
    const auto& b    = proj.build;
    const auto  base = std::filesystem::path(proj.project_dir);

    if (b.lync_main.empty()) return {};

    auto resolve = [&](const std::string& s) -> std::string {
        if (s.empty()) return {};
        auto p = std::filesystem::path(s);
        return (p.is_absolute() ? p : base / p).string();
    };

    // Compiler: project setting -> bundled <exe_dir>/lync/lync.exe -> PATH.
    std::string compiler = lync_fallback(b.lync_compiler, base, "lync.exe");
    if (compiler.empty()) compiler = "lync";   // last resort: PATH lookup

    const std::string main_f   = resolve(b.lync_main);
    const std::string plugin_f = lync_fallback(b.lync_plugin,  base, "zues_lync_plugin.dll");
    const std::string incl_f   = lync_fallback(b.lync_include, base, "include");
    const std::string prelude_f= lync_fallback(b.lync_prelude, base, "zues_api.lync");
    const std::string dll_f    = resolve(b.dll_path);

    auto q = [](const std::string& s) { return '"' + s + '"'; };

    std::string cmd = q(compiler) + ' ' + q(main_f) + " --target=dll";
    if (!plugin_f.empty())  cmd += " --plugin=" + q(plugin_f);
    if (!incl_f.empty())    cmd += " --include=" + q(incl_f);
    if (!prelude_f.empty()) cmd += " --prelude=" + q(prelude_f);
    if (!dll_f.empty())     cmd += " -o " + q(dll_f);
    // Always emit the symbol JSON next to the project so the editor can
    // pick it up post-build for type-aware autocomplete + param hints.
    {
        const auto sym_dir = base / ".zues";
        std::error_code ec; std::filesystem::create_directories(sym_dir, ec);
        const auto sym_path = (sym_dir / "symbols.json").string();
        cmd += " --emit-symbols=" + q(sym_path);
    }
    // Hand lync.exe an explicit stdlib path so `using std.math.*;` resolves.
    // Search order: (1) sibling of the lync compiler exe -- the deployed
    // dist layout puts stdlib at `<dist>/lync/stdlib/`; (2) the LyncLang
    // repo's stdlib for dev workflows where lync.exe is built in-tree.
    // First hit wins; if both miss, lync's own fallback (sibling of the
    // exe) takes over and may fail with "module not found" -- the user
    // will see that in the Console.
    {
        std::filesystem::path stdlib_dir;
        std::error_code ec;
        const std::filesystem::path comp_path(compiler);
        if (comp_path.is_absolute() || std::filesystem::exists(comp_path, ec)) {
            const auto sib = comp_path.parent_path() / "stdlib";
            if (std::filesystem::exists(sib, ec)) stdlib_dir = sib;
        }
        if (stdlib_dir.empty()) {
            // Walk up from the compiler dir looking for a LyncLang/stdlib
            // sibling -- typical when running out of a dev build tree.
            std::filesystem::path p = comp_path.parent_path();
            for (int i = 0; i < 6 && !p.empty(); ++i) {
                const auto cand = p / "stdlib";
                if (std::filesystem::exists(cand / "std.math.lync", ec)) {
                    stdlib_dir = cand; break;
                }
                if (p.parent_path() == p) break;
                p = p.parent_path();
            }
        }
        if (!stdlib_dir.empty())
            cmd += " --stdlib=" + q(stdlib_dir.string());
    }
    // run_capture (CreateProcess on Win, popen elsewhere) merges stderr
    // into the captured stdout pipe directly. No `2>&1` redirect, no outer
    // cmd.exe quote wrap — those were artifacts of the old _popen path.
    return cmd;
}

// ---------------------------------------------------------------------------

std::filesystem::path executable_dir() {
#if defined(_WIN32)
    char buf[MAX_PATH];
    DWORD n = ::GetModuleFileNameA(nullptr, buf, MAX_PATH);
    if (n == 0 || n == MAX_PATH) return std::filesystem::current_path();
    return std::filesystem::path(buf).parent_path();
#else
    char buf[PATH_MAX];
    ssize_t n = ::readlink("/proc/self/exe", buf, sizeof(buf) - 1);
    if (n <= 0) return std::filesystem::current_path();
    buf[n] = '\0';
    return std::filesystem::path(buf).parent_path();
#endif
}

void logf_info(const char* fmt, ...) {
    char buf[256];
    va_list ap; va_start(ap, fmt);
    std::vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    ZUES_LOG_INFO(buf);
}

void on_window_resized(const WindowResized& e) {
    logf_info("event WindowResized -> %dx%d", e.width, e.height);
}

// Build a small demo world the editor can show and operate on. Real project
// loading lands in Phase 4.2; for now the editor ships with this scene baked
// in so panels have something to render.
void build_demo_world(Engine::ecs::World& world) {
    using namespace Engine::ecs;
    using namespace Engine::components;

    world.register_builtins();
    const ComponentId Position_id   = world.register_component<Position>("Position");
    const ComponentId Velocity_id   = world.register_component<Velocity>("Velocity");
    const ComponentId Tag_Player_id = world.register_component<Tag_Player>("Tag_Player");
    (void)Tag_Player_id;

    auto root = world.create_entity();
    Name root_name{};
    std::snprintf(root_name.value, sizeof(root_name.value), "Scene Root");
    world.add_component(root, world.find_component_id("Name"), &root_name);
    Transform2D rt{};
    rt.position = {640, 360};
    world.add_component(root, world.find_component_id("Transform2D"), &rt);

    Camera2D cam{};
    cam.ortho_size = 10.0f;           // 10 units vertical visible
    cam.sort_mode  = SortMode::YDescending;
    auto cam_e = world.create_entity();
    Name cam_name{};
    std::snprintf(cam_name.value, sizeof(cam_name.value), "Main Camera");
    world.add_component(cam_e, world.find_component_id("Name"), &cam_name);
    world.add_component(cam_e, world.find_component_id("Transform2D"), &rt);
    world.add_component(cam_e, world.find_component_id("Camera2D"), &cam);
    world.set_parent(cam_e, root);

    // A few demo entities to populate the hierarchy + inspector.
    for (int i = 0; i < 4; ++i) {
        auto e = world.create_entity();
        Name n{};
        std::snprintf(n.value, sizeof(n.value), "Box %d", i);
        world.add_component(e, world.find_component_id("Name"), &n);

        Transform2D t{};
        t.position = {200.0f + i * 60.0f, 360.0f};
        t.scale = {1.0f, 1.0f};
        world.add_component(e, world.find_component_id("Transform2D"), &t);

        Position p{static_cast<float>(i) * 10.0f, 0.0f};
        world.add_component(e, Position_id, &p);

        if (i % 2 == 0) {
            Velocity v{1.0f, 0.0f};
            world.add_component(e, Velocity_id, &v);
        }

        world.set_parent(e, root);
    }
}

}  // namespace

int main(int argc, char** argv) {
    using namespace Engine;

    // ---- Parse args ---------------------------------------------------------
    const char* project_arg     = nullptr;
    const char* project_dll_arg = nullptr;   // explicit DLL override (for tests)
    for (int i = 1; i < argc; ++i) {
        if (std::strncmp(argv[i], "--project=", 10) == 0) {
            project_arg = argv[i] + 10;
        } else if (std::strncmp(argv[i], "--project-dll=", 14) == 0) {
            project_dll_arg = argv[i] + 14;
        }
    }

    Project project;
    bool   has_project = false;
    if (project_arg) {
        if (load_project(project_arg, project) == Result::Ok) {
            has_project = true;
        } else {
            std::fprintf(stderr, "[editor] failed to load project: %s\n", project_arg);
        }
    }

    const auto dir     = executable_dir();
    const auto dir_str = dir.string();

    EngineStartupDesc desc = {};
    desc.modules_dir = dir_str.c_str();
    desc.project_dll = "";

    if (engine_startup(desc) != Result::Ok) {
        std::fprintf(stderr, "engine_startup failed\n");
        return 1;
    }

    // Register IRenderCamera_v1 immediately after engine_startup. Other
    // services (and the editor's render system) consume it; safe to register
    // once the service registry exists.
    host::register_render_camera_service();

    ZUES_LOG_INFO("Zues editor booted - modules loaded");

    // Quick sanity smokes — same as before but condensed.
    events()->subscribe<WindowResized>(on_window_resized);
    events()->publish(WindowResized{1280, 720});

    auto* window   = static_cast<IWindow_v1*>(
        services()->get_service(ZUES_SERVICE_WINDOW_V1, ZUES_SERVICE_WINDOW_V1_VERSION));
    auto* renderer = static_cast<IRenderer_2D_v1*>(
        services()->get_service(ZUES_SERVICE_RENDERER_2D, ZUES_SERVICE_RENDERER_2D_VERSION));

    if (!window) {
        ZUES_LOG_WARN("No IWindow_v1 - editor needs a window. Exiting.");
        engine_shutdown();
        return 0;
    }

    // ---- ZUES_RENDERER_DEMO=1: skip ImGui, run the sprite batcher demo ----
    // Used to verify the renderer in isolation (visible sprites). The editor
    // path will display sprites inside the Scene FBO panel once 4.3 lands.
    if (const char* demo_env = std::getenv("ZUES_RENDERER_DEMO");
        demo_env && std::atoi(demo_env) != 0 && renderer) {
        ZUES_LOG_INFO("renderer demo mode - drawing 100 sprites/frame (no ImGui)");

        // Procedural 64x64 checker texture.
        constexpr int TEX = 64;
        std::vector<std::uint32_t> px(TEX * TEX);
        for (int y = 0; y < TEX; ++y) {
            for (int x = 0; x < TEX; ++x) {
                const bool checker = ((x / 8) + (y / 8)) % 2 == 0;
                px[y * TEX + x] = checker ? 0xFFEEEEEEu : 0xFF555555u;
            }
        }
        const ZuesTextureHandle tex = renderer->load_texture_from_memory(
            renderer, px.data(), TEX, TEX);

        int frame_cap = 0;
        if (const char* env = std::getenv("ZUES_FRAME_CAP")) frame_cap = std::atoi(env);
        int frames = 0;

        while (!window->should_close(window) && (frame_cap == 0 || frames < frame_cap)) {
            window->poll_events(window);
            renderer->begin_frame(renderer, 0.05f, 0.05f, 0.07f, 1.0f);

            for (int i = 0; i < 100; ++i) {
                const float t = frames * 0.02f + i * 0.13f;
                const float pulse = 80.0f + 16.0f * std::sin(t);
                const float cx = 80.0f + (i % 10) * 110.0f;
                const float cy = 60.0f + (i / 10) * 90.0f + 20.0f * std::sin(t * 0.7f);
                const float r = 0.5f + 0.5f * std::sin(t * 1.7f);
                const float g = 0.5f + 0.5f * std::sin(t * 1.7f + 2.0f);
                const float b = 0.5f + 0.5f * std::sin(t * 1.7f + 4.0f);
                renderer->draw_sprite(renderer, tex,
                                      cx - pulse * 0.5f, cy - pulse * 0.5f, pulse, pulse,
                                      0.0f, 0.0f, 1.0f, 1.0f,
                                      r, g, b, 1.0f);
            }
            renderer->end_frame(renderer);
            window->swap_buffers(window);
            ++frames;
        }
        renderer->free_texture(renderer, tex);
        engine_shutdown();
        return 0;
    }

    // ---- Editor state ----
    ecs::World world;
    // Demo world (Position / Velocity / Tag_Player + a few entities) only
    // when there's no project. Building it with a project loaded would push
    // these scratch component types under the "engine builtin" watermark,
    // which means unload_project_types() can't drop them on hot-reload and
    // they'd ghost in the Add Component picker forever.
    if (!has_project) {
        build_demo_world(world);
    }

    // Tracks whatever world ended up loaded into `world` during init. Set
    // by the project default-world path and the recent-worlds auto-load
    // fallback so we don't double-load and the editor's "current world"
    // breadcrumb survives subsequent Save / Save As cycles.
    std::string autoload_world_path;

    if (has_project) {
        char buf[256];
        std::snprintf(buf, sizeof(buf), "loaded project '%s' from %s",
                      project.name.c_str(), project.project_dir.c_str());
        ZUES_LOG_INFO(buf);

        // Don't load any world yet -- engine builtins (Transform2D, Name,
        // RigidBody, ...) and the project DLL's components both register
        // LATER (`world.register_builtins()` + `project_loader.load()`
        // below). Loading a world now would silently drop every saved
        // component because `find_component_id(...)` returns INVALID
        // until those registrations have happened. Just record a
        // candidate path; the actual load runs once everything is wired.
        if (!project.default_world.empty()) {
            std::filesystem::path wp =
                std::filesystem::path(project.project_dir) / project.default_world;
            std::error_code ec;
            if (std::filesystem::exists(wp, ec) && std::filesystem::is_regular_file(wp, ec)) {
                autoload_world_path = Engine::editor::path_str(wp);
            }
        }
    } else {
        ZUES_LOG_INFO("no --project arg; running with demo world");
    }

    editor::EditorState state;
    state.world = &world;
    state.renderer = renderer;
    state.project_loaded = has_project;
    if (has_project) {
        state.project_name = project.name;
        state.project_dir  = project.project_dir;
        state.project_default_language = project.default_language;
        state.project_worlds_dir       = project.worlds_dir;
        state.project_source_dir       = project.source_dir;
        state.source_root_relative     = project.source_dir;
        state.project_default_world    = project.default_world;
        state.project_window_width     = project.settings.window_width;
        state.project_window_height    = project.settings.window_height;
        state.project_fixed_size       = project.settings.fixed_size;
        state.project_fullscreen       = project.settings.fullscreen;

        // Build the asset registry. Walks <project>/assets, indexes every
        // recognised asset by guid (embedded for JSON-owned formats,
        // sidecar .meta for binaries). Subsequent prefab drag-drops, ref
        // resolves, and asset-aware drag targets read from this index.
        const auto assets_root = std::filesystem::path(project.project_dir) /
                                 state.assets_root_relative;
        const u32 indexed = AssetRegistry::instance().rescan(
            assets_root.string().c_str());
        log_write(LogLevel::Info, "asset_registry",
                  ("indexed " + std::to_string(indexed) + " assets").c_str());
    }
    state.exe_dir      = dir;
    state.recent_worlds = editor::load_recent_worlds(dir);

    // World autoload priority on editor start:
    //   1. recent_worlds[0] - the LAST world the user had open (saved or
    //      opened). This is what users expect: "open the editor, pick up
    //      where I left off". Wins over project.default_world because
    //      `default_world` is just the first-save fallback, while recents
    //      tracks every Open / Save action.
    //   2. project.default_world - if recents is empty (first session
    //      after creating the project, or after deleting recents.json).
    //   3. Whatever init already loaded into `world` (autoload_world_path).
    //
    // We aggressively REPLACE whatever init loaded if recents[0] is on
    // disk. The project's default_world load above was speculative; the
    // user's actual last-open beats it.
    // Same deferred-load story as project.default_world above: just pick
    // a candidate path now. The actual world load runs after register_builtins
    // and project_loader.load below, when find_component_id can resolve
    // every saved component name.
    if (!state.recent_worlds.empty()) {
        const auto& candidate = state.recent_worlds.front();
        std::error_code ec;
        if (std::filesystem::exists(candidate, ec) &&
            std::filesystem::is_regular_file(candidate, ec)) {
            autoload_world_path = candidate;
        }
    }

    // Seed the current-world breadcrumb from whichever world init loaded.
    if (!autoload_world_path.empty()) {
        state.current_world_path = editor::normalize_path(autoload_world_path);
    }

    // Same here -- defer to after register_builtins. Picks the first
    // viable recent if the candidate set above didn't resolve.
    if (autoload_world_path.empty() && !state.recent_worlds.empty()) {
        for (const auto& candidate : state.recent_worlds) {
            std::error_code ec;
            if (!std::filesystem::exists(candidate, ec) ||
                !std::filesystem::is_regular_file(candidate, ec)) continue;
            autoload_world_path = candidate;
            break;
        }
    }

    editor::install_log_sink(&state.log);
    // Item 3: restore previously open Lync tabs from %APPDATA%/Zues/recent_lync_tabs.json.
    editor::load_recent_lync_tabs(state);

    // Load editor icons (Play/Pause/Stop PNGs from assets/custom-icons).
    // Renderer is ready by this point — modules' on_ready fired during
    // engine_startup. Icons free at shutdown alongside the scene RT.
    editor::icons_load(state.icons, renderer);

    // ---- Resolve project DLL path ------------------------------------------
    // Priority: --project-dll override > project.build.dll_path > sample
    // (mygame.dll next to the editor binary).
    std::filesystem::path project_dll_path;
    if (project_dll_arg && *project_dll_arg) {
        project_dll_path = project_dll_arg;
    } else if (has_project && !project.build.dll_path.empty()) {
        project_dll_path =
            std::filesystem::path(project.project_dir) / project.build.dll_path;
    } else {
#if defined(_WIN32)
        project_dll_path = dir / "mygame.dll";
#else
        project_dll_path = dir / "mygame.so";
#endif
    }

    // ---- Project DLL load --------------------------------------------------
    // Wire the world into the host API thunks BEFORE the project's on_load
    // — the project will register components and spawn entities into it.
    // HostContext carries the bits HostShared needs; EditorState carries
    // the rest (UI state, undo, etc.).
    static host::HostContext host_ctx;
    host_ctx.world          = &world;
    host_ctx.project_dir    = project.project_dir;
    host_ctx.project_loaded = has_project;
    host::set_host_context(&host_ctx);

    const ZuesHostApi host_api = host::build_host_api();
    ZuesEngine* const engine_h = host::engine_handle();

    // If a project DLL exists, the demo content shouldn't share the world
    // with it — the user expects to see only their game's entities. Clear
    // the demo entities before on_load fires. Component types stay
    // registered (World::clear leaves the type registry intact), so any
    // builtin types (Transform2D, etc.) remain available to the project.
    {
        std::error_code ec;
        if (std::filesystem::exists(project_dll_path, ec)) {
            world.clear();
            ZUES_LOG_INFO("project DLL detected - cleared demo world");
        }
    }

    // Register engine builtins BEFORE the project DLL loads. The watermark
    // captured inside register_builtins() draws the line between "engine
    // owned" and "project registered" component types. Anything the project
    // registers via host->register_component lands beyond the watermark, so
    // unload_project_types() can drop it cleanly on hot-reload.
    world.register_builtins();

    host::ProjectDllLoader project_loader;
    const bool project_dll_ok =
        project_loader.load(project_dll_path, &host_api, engine_h);

    // ---- Deferred world autoload ------------------------------------------
    // Now that engine builtins (register_builtins above) AND the project
    // DLL's components (registered inside project_loader.load via the
    // host_register_component thunk) are both available, load the
    // candidate world we picked earlier. Loading any sooner silently
    // dropped every component because find_component_id returned
    // INVALID before this point.
    //
    // CRITICAL: if the project DLL failed to load (ABI mismatch, build
    // error, missing file), DO NOT touch the world file. Auto-loading
    // would parse the saved world, fail to recognise every project-side
    // component (find_component_id returns INVALID for unregistered
    // names), silently drop them, and the user's next Ctrl+S would
    // overwrite the file with the gutted state -- their custom data is
    // gone. Toast loudly so they know to fix the DLL before doing
    // anything else.
    if (!project_dll_ok && !project_dll_path.empty() &&
            !autoload_world_path.empty()) {
        ZUES_LOG_ERROR("project DLL did not load - skipping world autoload "
                       "to protect custom component data");

        // If the failure was specifically an ABI mismatch (DLL built
        // against an older engine), surface a prompt the user can
        // click "Rebuild" on -- much friendlier than asking them to go
        // touch a .lync file. The actual rebuild happens via the lync
        // watcher's force_fire path further down once they confirm.
        if (project_loader.last_failure_was_abi_mismatch()) {
            state.abi_mismatch_open       = true;
            state.abi_mismatch_observed   = project_loader.last_observed_abi();
            state.abi_mismatch_expected   = project_loader.last_expected_abi();
            // Hold onto the world path we WOULD have autoloaded so we
            // can retry it after the rebuild + reload succeeds.
            state.abi_pending_world_autoload = autoload_world_path;
        } else {
            editor::show_toast(state,
                "Project DLL failed to load. World autoload skipped so your "
                "custom components aren't wiped on next save. Rebuild the "
                "project DLL (touch a .lync file) and reopen.",
                8.0f, true);
        }
        // Mark the editor as save-locked so a stray Ctrl+S can't overwrite
        // the on-disk world with our partially-loaded state. Cleared once
        // the lync watcher rebuilds + reloads the DLL successfully.
        state.world_save_locked = true;
        autoload_world_path.clear();
    }
    // Wire the lazy-resolve path BEFORE the world autoload below.
    // Sprite.texture is a Handle field that round-trips as
    // [idx, gen, "guid_hex"]; the deserializer asks the registry to
    // map guid -> live GL handle, which falls through to this resolver
    // on miss. Setting it after the autoload meant every sprite came
    // back with the previous run's stale GL id and rendered blank
    // until something else (the asset browser thumb, the user
    // clicking the entity, ...) pushed a fresh load.
    struct ResolverCtx {
        ::IRenderer_2D_v1*           r;
        Engine::editor::EditorState* s;
    };
    static ResolverCtx g_resolver_ctx{ renderer, &state };
    Engine::AssetRegistry::instance().set_handle_resolver(
        +[](Engine::AssetKind kind, Engine::Guid g, void* user) -> Engine::u32 {
            if (kind != Engine::AssetKind::Texture) return 0;
            auto* ctx = static_cast<ResolverCtx*>(user);
            if (!ctx || !ctx->r || !ctx->r->load_texture_from_file) return 0;
            const char* path = Engine::AssetRegistry::instance().path_for(g);
            if (!path) return 0;
            std::string abs = ctx->s->project_dir;
            if (!abs.empty() && abs.back() != '/' && abs.back() != '\\') abs += '/';
            abs += ctx->s->assets_root_relative;
            if (!abs.empty() && abs.back() != '/' && abs.back() != '\\') abs += '/';
            abs += path;
            const Engine::u32 tex = ctx->r->load_texture_from_file(ctx->r, abs.c_str());
            if (tex) {
                Engine::AssetRegistry::instance()
                    .bind_runtime_handle(Engine::AssetKind::Texture, tex, g);
                const auto sett = Engine::AssetRegistry::instance()
                    .sprite_settings_for(g);
                if (ctx->r->set_texture_filter)
                    ctx->r->set_texture_filter(ctx->r, tex,
                        sett.filter == Engine::SpriteFilter::Nearest ? 1 : 0);
                if (ctx->r->set_texture_wrap) {
                    int w = 0;
                    if (sett.wrap == Engine::SpriteWrap::Repeat) w = 1;
                    else if (sett.wrap == Engine::SpriteWrap::Mirror) w = 2;
                    ctx->r->set_texture_wrap(ctx->r, tex, w);
                }
                Engine::editor::register_sprite_asset(*ctx->s, abs, tex);
                ctx->s->asset_thumb_cache[abs] = tex;
            }
            return tex;
        }, &g_resolver_ctx);

    if (!autoload_world_path.empty()) {
        std::error_code ec;
        if (std::filesystem::exists(autoload_world_path, ec) &&
            std::filesystem::is_regular_file(autoload_world_path, ec)) {
            std::ifstream in(autoload_world_path, std::ios::binary | std::ios::ate);
            if (in) {
                auto sz = in.tellg();
                in.seekg(0);
                std::vector<u8> bytes(static_cast<size_t>(sz));
                if (in.read(reinterpret_cast<char*>(bytes.data()), sz)) {
                    char first = 0;
                    for (auto b : bytes) {
                        if (b!=' '&&b!='\t'&&b!='\n'&&b!='\r') { first = (char)b; break; }
                    }
                    world.clear();
                    const Result res = (first == '{')
                        ? world.load_json(reinterpret_cast<const char*>(bytes.data()),
                                           bytes.size())
                        : world.load_binary(bytes.data(), bytes.size());
                    // Re-adopt the project's singleton entities -- world.clear
                    // erased the singletons map and load_json doesn't repopulate
                    // it. Without this, Hierarchy/Globals appears empty until
                    // the first user-side Singleton<T>() call lazily adopts.
                    host::resync_singletons();
                    if (res == Result::Ok) {
                        state.current_world_path =
                            editor::normalize_path(autoload_world_path);
                        char abuf[512];
                        std::snprintf(abuf, sizeof(abuf),
                                      "auto-loaded world: %s",
                                      autoload_world_path.c_str());
                        ZUES_LOG_INFO(abuf);
                    } else {
                        ZUES_LOG_WARN("autoload: world load failed");
                    }
                }
            }
        }
    }

    // ---- Lync source watcher setup ----------------------------------------
    // Only active when the project specifies a lync_main. Scan the initial
    // mtime so the watcher only fires on changes AFTER load, not immediately.
    if (has_project && !project.build.lync_main.empty()) {
        // Auto-generate the manifest at <project>/<source_dir>/_zues_main.lync
        // and override lync_main to point at it. This makes mygame.lync (and
        // any other user .lync files) become "modules" the manifest pulls in
        // via Lync's `include FileName.*` syntax. The user never edits the
        // manifest; the editor regenerates it whenever the .lync file set
        // in src/ changes.
        const std::filesystem::path proj_base(project.project_dir);
        const std::filesystem::path src_dir =
            proj_base / (project.source_dir.empty() ? "src" : project.source_dir);
        const std::filesystem::path manifest_path = src_dir / kZuesManifestName;
        // Sweep stale live-check temp files left behind by previous editor
        // sessions that crashed mid-worker. Cheap; runs once on project load.
        {
            std::error_code sec;
            for (auto& e : std::filesystem::directory_iterator(src_dir, sec)) {
                if (!e.is_regular_file(sec)) continue;
                const std::string n = Engine::editor::path_str(e.path().filename());
                if (n.find(".__live.") != std::string::npos)
                    std::filesystem::remove(e.path(), sec);
            }
        }
        regenerate_lync_manifest(src_dir, manifest_path);
        // Make the project's build use the manifest as the entry file.
        std::error_code rel_ec;
        project.build.lync_main =
            std::filesystem::relative(manifest_path, proj_base, rel_ec).string();
        if (rel_ec || project.build.lync_main.empty())
            project.build.lync_main = Engine::editor::path_str(manifest_path);
        project.build.lync_main = editor::normalize_path(project.build.lync_main);
        logf_info("lync manifest: %s", project.build.lync_main.c_str());

        auto& lw      = state.lync_watch;
        lw.project_dir = project.project_dir;
        lw.build_cmd   = build_lync_cmd(project);
        lw.last_mtime  = scan_lync_mtime(lw.project_dir);
        if (lw.active()) {
            ZUES_LOG_INFO("lync watcher: active - polling .lync sources every 0.5s");
        } else {
            ZUES_LOG_WARN("lync watcher: lync_main set but command build failed; check project config");
        }

        // Snapshot compiler bits for the in-editor live syntax checker.
        const auto& b = project.build;
        const auto base = std::filesystem::path(project.project_dir);
        auto resolve = [&](const std::string& s) -> std::string {
            if (s.empty()) return {};
            auto p = std::filesystem::path(s);
            return (p.is_absolute() ? p : base / p).string();
        };
        // Same fallback chain as build_lync_cmd so the live syntax check
        // sees the bundled lync next to editor.exe in packaged builds.
        state.lync_compiler_abs = lync_fallback(b.lync_compiler, base, "lync.exe");
        if (state.lync_compiler_abs.empty()) state.lync_compiler_abs = "lync";
        state.lync_plugin_abs   = lync_fallback(b.lync_plugin,  base, "zues_lync_plugin.dll");
        state.lync_include_abs  = lync_fallback(b.lync_include, base, "include");
        state.lync_prelude_abs  = lync_fallback(b.lync_prelude, base, "zues_api.lync");
        // Count lines in the prelude so the diagnostic parser can subtract
        // the offset from `mygame.lync:96` style errors (lync's lexer treats
        // prelude+source as one buffer and reports combined line numbers).
        if (!state.lync_prelude_abs.empty()) {
            std::ifstream f(state.lync_prelude_abs);
            int n = 0; std::string line;
            while (std::getline(f, line)) ++n;
            state.lync_prelude_lines = n;
        }
    }

    // (Engine builtins are now registered earlier, before project_loader.load,
    // so the project's component-type watermark sits at the right offset.)

    // Install editor's standard systems (camera publish + sprite render).
    // After register_builtins so component IDs resolve immediately.
    editor::register_editor_systems(world, state);

    // Debug-draw service. Engine subsystems publish gizmos through
    // this service; we forward to the editor's gizmo renderer.
    // Categories (Particles / Animator / Audio / ...) toggleable
    // from the View menu.
    editor::register_debug_draw_service();

    // (The Handle resolver was registered earlier, before the world
    // autoload, so Sprite.texture handles deserialise to live GL ids
    // on first load.)

    // After any world load, walk every entity with a Sprite and make
    // sure its texture is in the editor's sprite_registry (the
    // dropdown the inspector matches against). The Handle deserializer
    // already resolves the guid -> live GL handle, but the lazy
    // resolver only registers when it actually loaded the texture --
    // a second world load that hits an existing binding skips the
    // register_sprite_asset() call and the inspector ends up showing
    // "(unregistered texture)" until thumb_for runs. Fixing it once
    // here keeps every load path consistent.
    auto sync_sprite_registry = [&](Engine::ecs::World& w) {
        const auto sprite_id = w.find_component_id("Sprite");
        if (!sprite_id) return;
        auto* r = static_cast<IRenderer_2D_v1*>(state.renderer);
        if (!r) return;

        struct Ctx {
            Engine::editor::EditorState* s;
        } ctx{ &state };
        const Engine::ecs::ComponentId required[] = { sprite_id };
        w.iterate_query(required, 1, nullptr, 0,
            +[](void* user, Engine::ecs::Entity, void** cols, Engine::u32) {
                auto* c  = static_cast<Ctx*>(user);
                auto* sp = static_cast<Engine::components::Sprite*>(cols[0]);
                if (!sp || sp->texture.index == 0) return;
                const Engine::Guid g = Engine::AssetRegistry::instance()
                    .guid_for_runtime_handle(Engine::AssetKind::Texture,
                                              sp->texture.index);
                if (g.is_null()) return;
                const char* path =
                    Engine::AssetRegistry::instance().path_for(g);
                if (!path) return;
                std::string abs = c->s->project_dir + "/"
                                + c->s->assets_root_relative + "/"
                                + path;
                Engine::editor::register_sprite_asset(*c->s, abs,
                    sp->texture.index);
                c->s->asset_thumb_cache[abs] = sp->texture.index;
            }, &ctx);
    };
    // Cover the autoload above (which ran before this lambda was
    // defined). Subsequent load sites call sync_sprite_registry(world)
    // themselves.
    sync_sprite_registry(world);

    static host::SpriteRenderSystem g_sprite_render;
    g_sprite_render.register_into(world, renderer);

    // Animator system: ticks Animator components in Play mode only.
    // Drives Sprite.texture + slice rect from the active .zanim's
    // current frame.
    static host::AnimatorSystem g_animator;
    g_animator.register_into(world, renderer);

    // Particles (CPU tier today; GPU-compute tier in a future slice).
    // Update runs in PreUpdate (Game), Render runs in Render (Both) so
    // the editor previews emitters in edit mode too.
    static host::ParticleSystem g_particles;
    g_particles.register_into(world, renderer);

    // Audio system: miniaudio device + ECS sync for AudioSource /
    // AudioListener. Runs in both Edit and Play (so the editor's preview
    // play button works), publishes range gizmos for the selected
    // AudioSource via IDebugDraw_v1 (category ZUES_DBG_AUDIO).
    static host::AudioSystem g_audio;
    g_audio.init(world);

    // HUD pass for UIAnchor + Text / Sprite. Same path as the runtime so
    // what the editor previews in the Game panel matches the exported
    // game pixel-for-pixel. Default font is searched in: the loaded
    // project's assets/, the editor exe's assets/, and the build-time
    // bundled assets dir (ZUES_ASSETS_DIR_DEFAULT, set by Editor's CMake).
    static host::UIRenderSystem g_ui_render;
    {
        const std::string proj_assets = has_project
            ? (std::filesystem::path(project.project_dir) / "assets").string()
            : std::string{};
        const std::string engine_assets = (dir / "assets").string();
        const std::string bundle_assets = ZUES_ASSETS_DIR_DEFAULT;
        g_ui_render.register_into(world, renderer,
            { proj_assets, engine_assets, bundle_assets });
    }

    // Spawn a few demo sprites + a Main Camera so the Scene viewport has
    // visible content when there's NO project loaded. With a project loaded,
    // the project owns the world: the editor stays out of it. Without this
    // gate the demo entities + camera persisted across project reloads and
    // duplicated alongside the project's own entities every Ctrl+R.
    if (!has_project) {
        editor::spawn_editor_demo_sprites(world);
    }

    // ---- ImGui ----
    auto* glfw_window = static_cast<GLFWwindow*>(window->native_handle(window));
    if (!editor::imgui_init(glfw_window)) {
        ZUES_LOG_ERROR("ImGui init failed");
        engine_shutdown();
        return 1;
    }
    editor::theme_apply_dark_minimal();

    ZUES_LOG_INFO("ImGui ready - entering editor loop");

    // Frame cap = sanity net for headless testing. In normal use the user
    // closes the window with ESC or the title-bar X. Set ZUES_FRAME_CAP
    // env var to override (or 0 for unlimited).
    int frame_cap = 0;
    if (const char* env = std::getenv("ZUES_FRAME_CAP")) frame_cap = std::atoi(env);
    int frames = 0;

    bool   prev_is_playing = false;             // for Play/Stop transitions
    double last_frame_time = glfwGetTime();     // for real-dt computation

    while (!window->should_close(window) && (frame_cap == 0 || frames < frame_cap)) {
        window->poll_events(window);

        // ---- Drain OS file drops -----------------------------------------
        // Files dragged onto the editor window from File Explorer / Finder
        // get queued by the window module. Import each image into the
        // currently-visible asset folder; non-image drops fall through.
        if (window->dropped_paths_count) {
            const int dropped = window->dropped_paths_count(window);
            if (dropped > 0 && state.project_loaded) {
                editor::handle_dropped_files(state, window, dropped);
            }
            if (dropped > 0) window->clear_dropped_paths(window);
        }

        // ---- Detect Edit↔Play transitions ----
        // Snapshot world bytes on Edit→Play, restore on Play→Stop. Component
        // types and systems persist across clear+load (clear() preserves the
        // type registry, load_binary() requires it pre-registered) so the
        // project DLL's cached IDs stay valid.
        if (state.is_playing && !prev_is_playing) {
            state.play_snapshot = world.save_binary();
            ZUES_LOG_INFO("play: scene snapshot taken");

            // Wire collision callbacks for the live project. The LyncPlugin
            // emits dispatch stubs (`__zues_on_collision` etc.) into the
            // project DLL whenever the user declares [OnCollision] /
            // [OnTriggerEnter] / [OnTriggerExit] functions. Those stubs
            // hang off ZuesProjectApi; we forward them to the physics
            // service so the post-step drain can fire them per event.
            //
            // Falls back to a console logger when the project doesn't
            // export any of the three - useful during early scene
            // bring-up before any user code reacts to collisions.
            if (auto* phys = static_cast<IPhysics_v1*>(
                    Engine::services()->get_service(ZUES_SERVICE_PHYSICS,
                                                    ZUES_SERVICE_PHYSICS_VERSION))) {
                if (phys->set_collision_handlers) {
                    const ZuesProjectApi* papi = project_loader.api();
                    ZuesEngine*           peng = project_loader.engine();
                    struct ProjCtx {
                        const ZuesProjectApi* api;
                        ZuesEngine*           eng;
                    };
                    static ProjCtx s_proj_ctx;   // static so the address survives
                    s_proj_ctx.api = papi;
                    s_proj_ctx.eng = peng;

                    auto fwd_collision = +[](void* u, uint32_t ai, uint32_t ag,
                                                  uint32_t bi, uint32_t bg) {
                        auto* c = static_cast<ProjCtx*>(u);
                        ZuesEntity a{ai, ag};
                        ZuesEntity b{bi, bg};
                        if (c && c->api && c->api->on_collision)
                            c->api->on_collision(c->eng, a, b);
                        else {
                            char buf[128];
                            std::snprintf(buf, sizeof(buf),
                                "collision: entity %u <-> %u", ai, bi);
                            Engine::log_write(Engine::LogLevel::Info, "phys", buf);
                        }
                    };
                    auto fwd_enter = +[](void* u, uint32_t si, uint32_t sg,
                                              uint32_t oi, uint32_t og) {
                        auto* c = static_cast<ProjCtx*>(u);
                        ZuesEntity self{si, sg};
                        ZuesEntity other{oi, og};
                        if (c && c->api && c->api->on_trigger_enter)
                            c->api->on_trigger_enter(c->eng, self, other);
                        else {
                            char buf[128];
                            std::snprintf(buf, sizeof(buf),
                                "trigger enter: %u entered %u", oi, si);
                            Engine::log_write(Engine::LogLevel::Info, "phys", buf);
                        }
                    };
                    auto fwd_exit = +[](void* u, uint32_t si, uint32_t sg,
                                             uint32_t oi, uint32_t og) {
                        auto* c = static_cast<ProjCtx*>(u);
                        ZuesEntity self{si, sg};
                        ZuesEntity other{oi, og};
                        if (c && c->api && c->api->on_trigger_exit)
                            c->api->on_trigger_exit(c->eng, self, other);
                        else {
                            char buf[128];
                            std::snprintf(buf, sizeof(buf),
                                "trigger exit: %u left %u", oi, si);
                            Engine::log_write(Engine::LogLevel::Info, "phys", buf);
                        }
                    };
                    phys->set_collision_handlers(phys, &s_proj_ctx,
                                                  fwd_collision, fwd_enter, fwd_exit);
                }
            }
        } else if (!state.is_playing && prev_is_playing) {
            if (!state.play_snapshot.empty()) {
                world.clear();
                if (world.load_binary(state.play_snapshot.data(),
                                      state.play_snapshot.size()) == Result::Ok) {
                    ZUES_LOG_INFO("stop: scene restored from snapshot");
                } else {
                    ZUES_LOG_WARN("stop: snapshot restore failed");
                }
            }
            state.play_snapshot.clear();
            state.is_paused = false;

            // Drop collision handlers so a stale ProjCtx doesn't outlive a
            // hot reload. Next Play re-binds with the fresh project pointer.
            // Also reset the b2World - bodies created during the play
            // session would otherwise leak into the next Play.
            if (auto* phys = static_cast<IPhysics_v1*>(
                    Engine::services()->get_service(ZUES_SERVICE_PHYSICS,
                                                    ZUES_SERVICE_PHYSICS_VERSION))) {
                if (phys->set_collision_handlers) {
                    phys->set_collision_handlers(phys, nullptr,
                                                  nullptr, nullptr, nullptr);
                }
                if (phys->reset_world) phys->reset_world(phys);
            }
        }
        prev_is_playing = state.is_playing;

        // ---- World save / load (deferred from File menu) ---------------
        // Blocked during Play to avoid corrupting the in-flight snapshot.
        if (!state.is_playing) {
            // Open World / Recent Worlds
            if (!state.want_load_world_path.empty()) {
                const std::string path = std::move(state.want_load_world_path);
                state.want_load_world_path.clear();

                std::ifstream in(path, std::ios::binary | std::ios::ate);
                if (in) {
                    const auto sz = in.tellg();
                    in.seekg(0);
                    std::vector<u8> bytes(static_cast<std::size_t>(sz));
                    in.read(reinterpret_cast<char*>(bytes.data()), sz);
                    world.clear();
                    // Detect format: JSON files start with '{' (after any
                    // whitespace). Binary files start with the magic bytes.
                    auto first_nonws = [&]() -> char {
                        for (auto b : bytes) {
                            if (b!=' '&&b!='\t'&&b!='\n'&&b!='\r') return (char)b;
                        }
                        return 0;
                    };
                    const Result res = (first_nonws() == '{')
                        ? world.load_json(reinterpret_cast<const char*>(bytes.data()),
                                           bytes.size())
                        : world.load_binary(bytes.data(), bytes.size());
                    if (res == Result::Ok) {
                        state.current_world_path = editor::normalize_path(path);
                        state.selected_entity    = {};
                        state.world_dirty        = false;
                        editor::record_recent_world(dir, state.recent_worlds, path);
                        sync_sprite_registry(world);
                        editor::show_toast(state, "World loaded", 2.5f, false);
                    } else {
                        // Don't fall back to build_demo_world here - it would
                        // re-register Position / Velocity / Tag_Player under
                        // the engine builtin watermark and ghost them in the
                        // Add Component picker forever. Just leave the world
                        // empty and tell the user the load failed.
                        ZUES_LOG_WARN("load_binary failed - world cleared");
                        editor::show_toast(state,
                            "Load failed (corrupt or schema mismatch)",
                            3.0f, true);
                    }
                } else {
                    editor::show_toast(state, "Could not open file", 2.5f, true);
                }
            }

            // Save World / Save World As
            const std::string save_path =
                !state.want_save_world_path.empty() ? state.want_save_world_path
                : (state.want_save_world             ? state.current_world_path
                                                      : std::string{});
            state.want_save_world      = false;
            state.want_save_world_path.clear();

            if (!save_path.empty() && state.world_save_locked) {
                // Save explicitly blocked because the project DLL didn't
                // load -- writing now would persist a world missing every
                // project component. Toast loudly and bail.
                editor::show_toast(state,
                    "Save blocked: project DLL is not loaded. Fix the DLL "
                    "first, then save.", 5.0f, true);
            } else if (!save_path.empty()) {
                // JSON now the default world format - VCS friendly + diffable.
                // Binary save_binary() still exists for build-time export.
                const std::string text = world.save_json();
                std::ofstream out(save_path, std::ios::binary);
                if (out.write(text.data(),
                              static_cast<std::streamsize>(text.size()))) {
                    state.current_world_path = editor::normalize_path(save_path);
                    state.world_dirty        = false;
                    editor::record_recent_world(dir, state.recent_worlds, save_path);
                    editor::show_toast(state, "World saved", 2.0f, false);

                    // First-save auto-promote: if the project has no
                    // default_world yet and we just wrote one INSIDE the
                    // project directory, set it as default + persist to
                    // .zuesproject. Subsequent saves don't touch the
                    // setting (the user can change it later from Project
                    // Settings).
                    if (has_project && project.default_world.empty()) {
                        std::error_code rec;
                        const auto rel = std::filesystem::relative(
                            save_path, project.project_dir, rec);
                        if (!rec && !rel.empty()) {
                            project.default_world = rel.string();
                            // Normalize separators for the json file.
                            for (auto& c : project.default_world)
                                if (c == '\\') c = '/';
                            const auto proj_file = std::filesystem::path(project.project_dir)
                                / (project.name + ".zuesproject");
                            Engine::save_project(Engine::editor::path_str(proj_file).c_str(), project);
                            ZUES_LOG_INFO("default_world set to first saved world");
                        }
                    }
                } else {
                    editor::show_toast(state, "Save failed", 2.5f, true);
                }
            }
        }

        // ---- Hot reload check -----------------------------------------
        // Two trigger paths:
        //   1) Manual: File→Reload Project or Ctrl+R sets want_manual_reload
        //   2) Auto: poll the source DLL's mtime ~2× per second; if it
        //      changed and we're in Edit mode, reload.
        // Reload during Play is intentionally disabled (state would
        // disappear mid-playtest, confusing). User must Stop first.
        bool should_reload = state.want_manual_reload && !state.is_playing;
        state.want_manual_reload = false;

        // ---- Build → Export ---------------------------------------------
        // Driven by the Build menu / shortcut. Runs once on the next tick
        // (rather than inline from the menu draw) so the toast it produces
        // posts cleanly outside the ImGui sub-menu's frame state.
        if (state.want_build_export) {
            state.want_build_export = false;
            (void)editor::build_export(state, state.build_export_kind);
        }

        if (state.auto_reload_enabled && !state.is_playing) {
            state.reload_poll_accum += state.last_dt;
            if (state.reload_poll_accum >= 0.5f) {
                state.reload_poll_accum = 0.0f;
                if (project_loader.is_source_dirty()) should_reload = true;
            }
        }

        if (should_reload) {
            state.selected_entity = ecs::Entity{};

            int alive_before = 0;
            world.iterate_alive([&](ecs::Entity){ ++alive_before; });

            // Per-type audit: snapshot how many entities currently HOLD
            // each registered component type. After the reload restores,
            // we'll diff and warn LOUDLY if any type came back with fewer
            // instances. That's the user's "RigidBody data disappeared
            // after rebuild" signal -- we surface it as a toast + Warn
            // instead of letting them notice in the Inspector hours later.
            std::map<std::string, int> count_before;
            world.iterate_component_types(
                [&](ecs::ComponentId id, const ecs::ComponentType& t) {
                    if (!t.name) return;
                    int n = 0;
                    const ecs::ComponentId required[] = { id };
                    world.iterate_query(required, 1, nullptr, 0,
                        +[](void* u, ecs::Entity, void**, Engine::u32){
                            ++*static_cast<int*>(u);
                        }, &n);
                    if (n > 0) count_before[t.name] = n;
                });

            const std::string snapshot = world.save_json();
            char rlog[512];
            std::snprintf(rlog, sizeof(rlog),
                "reload: snapshot %d alive entities (%zu json bytes)",
                alive_before, snapshot.size());
            Engine::log_write(Engine::LogLevel::Info, "editor.project", rlog);

            // Persist snapshot to a recovery file. If the in-memory
            // restore wipes entities for any reason, the user can grab
            // this file and Open World it to get their scene back.
            // Lives in `<exe_dir>/_zues_reload_backup.zworld`.
            {
                const auto backup =
                    state.exe_dir / "_zues_reload_backup.zworld";
                std::ofstream bf(backup, std::ios::binary);
                if (bf) {
                    bf.write(snapshot.data(),
                             static_cast<std::streamsize>(snapshot.size()));
                }
            }

            world.clear();
            world.unload_project_types();
            state.world_dirty = false;

            const bool ok = project_loader.reload();
            if (ok) {
                // DLL is healthy again -- save lock cleared. The user's
                // next Ctrl+S will write the live world to disk normally.
                state.world_save_locked = false;
            }

            if (ok && !snapshot.empty()) {
                // Project's on_load may have spawned its own demo
                // entities; load_json calls clear() at the start so
                // those get wiped before our restore runs.
                const Result lr = world.load_json(snapshot.data(), snapshot.size());
                if (lr == Result::Ok) sync_sprite_registry(world);
                int alive_after = 0;
                world.iterate_alive([&](ecs::Entity){ ++alive_after; });
                std::snprintf(rlog, sizeof(rlog),
                    "reload: restore %s, %d alive after (was %d before)",
                    lr == Result::Ok ? "OK" : "FAILED",
                    alive_after, alive_before);
                Engine::log_write(
                    lr == Result::Ok && alive_after >= alive_before
                        ? Engine::LogLevel::Info : Engine::LogLevel::Warn,
                    "editor.project", rlog);

                // Per-type audit (continued from `count_before`). Recount
                // after restore; any type whose population shrank is a
                // silent data-loss event -- log Warn per type AND surface
                // a sticky toast so the user actually notices.
                {
                    std::map<std::string, int> count_after;
                    world.iterate_component_types(
                        [&](ecs::ComponentId id, const ecs::ComponentType& t) {
                            if (!t.name) return;
                            int n = 0;
                            const ecs::ComponentId required[] = { id };
                            world.iterate_query(required, 1, nullptr, 0,
                                +[](void* u, ecs::Entity, void**, Engine::u32){
                                    ++*static_cast<int*>(u);
                                }, &n);
                            if (n > 0) count_after[t.name] = n;
                        });

                    int total_lost   = 0;
                    int types_lost   = 0;
                    std::string first_lost_summary;
                    for (const auto& [name, before] : count_before) {
                        const int after = count_after.count(name)
                                          ? count_after.at(name) : 0;
                        if (after < before) {
                            const int lost = before - after;
                            total_lost += lost;
                            ++types_lost;
                            if (first_lost_summary.empty()) {
                                first_lost_summary = name + " (" +
                                    std::to_string(after) + "/" +
                                    std::to_string(before) + ")";
                            }
                            char tlog[256];
                            std::snprintf(tlog, sizeof(tlog),
                                "reload: component '%s' dropped %d instance%s "
                                "(was %d, now %d)",
                                name.c_str(), lost, lost == 1 ? "" : "s",
                                before, after);
                            Engine::log_write(Engine::LogLevel::Warn,
                                              "editor.project", tlog);
                        }
                    }
                    if (types_lost > 0) {
                        char tt[384];
                        std::snprintf(tt, sizeof(tt),
                            "DATA LOSS: %d %s (incl. %s) lost %d instance%s "
                            "across reload. See Console + "
                            "_zues_reload_backup.zworld.",
                            types_lost,
                            types_lost == 1 ? "component type" : "component types",
                            first_lost_summary.c_str(),
                            total_lost,
                            total_lost == 1 ? "" : "s");
                        editor::show_toast(state, tt, 12.0f, true);
                    }
                }

                // If we lost entities AND the user had something on disk
                // already, suggest the path to recover from.
                if (alive_after < alive_before) {
                    std::snprintf(rlog, sizeof(rlog),
                        "reload: %d entities were dropped during restore; "
                        "your scene survives on disk in '_zues_reload_backup.zworld' "
                        "(next to editor.exe). File -> Open World to recover.",
                        alive_before - alive_after);
                    Engine::log_write(Engine::LogLevel::Warn, "editor.project", rlog);
                }
            } else if (!ok) {
                Engine::log_write(Engine::LogLevel::Warn, "editor.project",
                    "reload: project load failed; world cleared but snapshot "
                    "NOT restored (recover from _zues_reload_backup.zworld via "
                    "File -> Open World once the project compiles)");
            }
            editor::show_toast(state, ok ? "Project reloaded" : "Reload failed",
                               2.5f, !ok);
        }

        // ---- Lync source watcher + auto-compile ---------------------------
        // Save-driven first: the editor's save_doc sets `force_fire = true`
        // when the user writes a .lync to disk. We compile immediately on
        // that signal (no waiting for an mtime poll cycle).
        //
        // The mtime poll runs at a slow 5s cadence as a SAFETY NET for
        // external edits (user saved with another editor). Was 0.5s, which
        // felt like the compiler was running constantly.
        // Disabled during Play so a recompile doesn't interrupt a playtest.
        if (state.lync_watch.active() && !state.is_playing) {
            auto& lw = state.lync_watch;
            lw.poll_accum += state.last_dt;
            if (lw.cooldown > 0.0f) lw.cooldown -= state.last_dt;

            bool should_compile = false;
            if (lw.force_fire && lw.cooldown <= 0.0f) {
                // Editor just saved a .lync. Compile unconditionally.
                should_compile = true;
                lw.force_fire = false;
                lw.last_mtime = scan_lync_mtime(lw.project_dir);
            } else if (lw.poll_accum >= 5.0f && lw.cooldown <= 0.0f) {
                lw.poll_accum = 0.0f;
                const auto cur_mtime = scan_lync_mtime(lw.project_dir);
                if (cur_mtime != lw.last_mtime &&
                    cur_mtime != std::filesystem::file_time_type{}) {
                    should_compile = true;
                    lw.last_mtime = cur_mtime;
                }
            }

            if (should_compile) {
                lw.cooldown = 1.0f;   // suppress re-trigger for 1s
                {
                    {
                        (void)0;
                        // Refresh the auto-include manifest before compile -
                        // catches new files / renames since last tick. Cheap
                        // (just a directory listing + content compare).
                        {
                            const std::filesystem::path pb(project.project_dir);
                            const std::filesystem::path src_dir =
                                pb / (project.source_dir.empty() ? "src" : project.source_dir);
                            regenerate_lync_manifest(src_dir,
                                                      src_dir / kZuesManifestName);
                        }

                        // Log at INFO so the Console clearly shows the
                        // watcher fired - useful for diagnosing "save doesn't
                        // rebuild" issues. The toast is short-lived; the log
                        // line is the durable signal.
                        Engine::log_write(Engine::LogLevel::Info, "lync",
                                          "source changed - compiling...");
                        editor::show_toast(state, "Compiling...", 10.0f, false);

                        std::string captured;
                        const int rc = Engine::editor::run_capture(lw.build_cmd, captured);

                        // Resolve the project's lync_main absolute path so the
                        // watcher only clears markers for that one file on
                        // success (other docs may have live-check markers).
                        std::string primary = project.build.lync_main;
                        if (!primary.empty()) {
                            std::filesystem::path pp(primary);
                            if (!pp.is_absolute())
                                pp = std::filesystem::path(project.project_dir) / pp;
                            primary = pp.string();
                            for (auto& c : primary) if (c == '\\') c = '/';
                        }
                        if (rc == 0) {
                            Engine::log_write(Engine::LogLevel::Info, "lync",
                                              "compile OK");
                            editor::show_toast(state, "Compiled OK", 2.5f, false);
                            editor::apply_lync_diagnostics_watcher(state, "", true, primary);
                            // Pull the freshly-emitted JSON symbol table into
                            // ProjectSymbols so type-aware autocomplete and
                            // UFCS-correct param hints can use it on the next
                            // keystroke.
                            const auto sym_path = (std::filesystem::path(
                                project.project_dir) / ".zues" / "symbols.json").string();
                            editor::load_lync_symbols_json(state, sym_path);
                            // DLL mtime now changed - is_source_dirty() picks it
                            // up on the next 0.5s poll cycle and triggers reload.
                        } else {
                            char errbuf[1024];
                            std::snprintf(errbuf, sizeof(errbuf),
                                          "lync: compile failed (exit %d):\n%s",
                                          rc, captured.c_str());
                            Engine::log_write(Engine::LogLevel::Error,
                                              "lync", errbuf);
                            editor::show_toast(state,
                                               "Compile failed (see Console)",
                                               4.0f, true);
                            editor::apply_lync_diagnostics_watcher(state, captured, false, primary);
                        }
                    }
                }
            }
        }

        // Sync world tick mode from the editor's Play/Stop state. Editor-
        // and Game-domain systems are filtered inside World::tick_phase.
        world.set_tick_mode(state.is_playing ? ecs::TickMode::Play
                                              : ecs::TickMode::Edit);

        // Per-frame tick. Render + UiRender are SKIPPED here — they're
        // driven by panel_scene and panel_game inside their own bound RTs.
        // While paused, skip the simulation phases entirely; viewports keep
        // drawing the frozen state via their own tick_phase(Render) calls.
        //
        // Real dt via glfwGetTime, clamped to 100ms so a debugger pause or
        // OS hiccup doesn't blast game state with a 5-second tick.
        const double now = glfwGetTime();
        float frame_dt   = static_cast<float>(now - last_frame_time);
        last_frame_time  = now;
        if (frame_dt > 0.1f) frame_dt = 0.1f;
        state.last_dt = frame_dt;
        const bool simulating = !(state.is_playing && state.is_paused);
        if (simulating) {
            if (state.is_playing) project_loader.tick(frame_dt);

            // Physics step. Service is registered by zues_physics_box2d at
            // module load. We sandwich it between PreUpdate (gameplay reads
            // input + applies impulses) and Update (gameplay reacts to new
            // positions / collisions). The pre/post calls handle body
            // creation + transform sync; step advances the b2World.
            //
            // Game-only: physics runs ONLY when Play is engaged. In edit
            // mode bodies stay frozen so designers can place rigid bodies
            // without them tumbling under gravity. The pre_step body-
            // creation pass is also gated - we don't want Box2D's internal
            // state diverging from the editor's positions while paused.
            const bool run_physics = state.is_playing;
            auto* phys_svc = run_physics ? static_cast<IPhysics_v1*>(
                Engine::services()->get_service(ZUES_SERVICE_PHYSICS,
                                                ZUES_SERVICE_PHYSICS_VERSION)) : nullptr;
            for (u32 p = 0; p < static_cast<u32>(ecs::Phase::Render); ++p) {
                if (phys_svc && static_cast<ecs::Phase>(p) == ecs::Phase::Physics) {
                    phys_svc->pre_step (phys_svc, &world, frame_dt);
                    phys_svc->step     (phys_svc, frame_dt);
                    phys_svc->post_step(phys_svc, &world, frame_dt);
                }
                // Timers fire after PreUpdate -- gameplay code reads input
                // there, so a timer scheduled this frame won't fire until the
                // next, but a timer scheduled by [OnLoad] / a previous tick
                // sees its callback run before Update / Physics this frame.
                if (state.is_playing &&
                    static_cast<ecs::Phase>(p) == ecs::Phase::PreUpdate) {
                    host::tick_timers(frame_dt);
                }
                world.tick_phase(static_cast<ecs::Phase>(p), frame_dt);
            }
        }

        // Background clear — panels render on top of this.
        if (renderer) renderer->begin_frame(renderer, 0.05f, 0.05f, 0.07f, 1.0f);

        editor::imgui_begin_frame();
        editor::draw_dockspace();
        editor::draw_main_menu_bar(state);
        editor::draw_hierarchy_panel(state);
        editor::draw_inspector_panel(state);
        editor::draw_console_panel(state);
        editor::draw_scene_panel(state);
        editor::draw_game_panel(state);
        editor::draw_systems_panel(state);
        editor::draw_assets_panel(state);
        editor::draw_audio_panel(state);
        editor::draw_cue_editor_panel(state);
        editor::draw_todos_panel(state);
        editor::draw_lync_editor_panel(state);
        editor::draw_world_dialog(state);
        editor::draw_confirm_modal(state);
        editor::draw_docs_panel(state);
        editor::draw_project_settings_panel(state);
        editor::draw_search_panel(state);
        editor::draw_sprite_cutter(state);
        editor::draw_animation_editor(state);
        editor::draw_hotkeys_overlay(state);

        // Particles editor-mode preview. The Editor-domain preview
        // system in HostShared ticks ONLY this entity, so the user
        // sees the emitter animate while it's selected without having
        // to enter Play. Cleared (null entity) = no preview work.
        {
            const auto sel = state.selected_entity;
            const auto pid = world.find_component_id("Particles");
            if (pid && state.world && state.world->is_alive(sel) &&
                state.world->has_component(sel, pid)) {
                g_particles.set_preview_entity(sel);
            } else {
                g_particles.set_preview_entity(ecs::Entity{});
            }
        }

        // Push selection to the debug-draw service so subsystems can
        // do "draw only when selected" filtering.
        editor::debug_draw_set_selected(state.selected_entity);
        g_audio.set_selected_entity(state.selected_entity);

        // F1 toggles the hotkeys overlay. Global -- works regardless
        // of which panel has focus. Same idea as Unity's "Help"
        // menu but always one keypress away.
        if (ImGui::IsKeyPressed(ImGuiKey_F1, false)) {
            state.show_hotkeys = !state.show_hotkeys;
        }

        // ---- ABI mismatch recovery prompt ----------------------------
        // Shown once at boot when the project DLL was built against a
        // different engine API version. Offers a one-click rebuild via
        // the existing Lync watcher path: setting force_fire = true
        // makes the watcher's next tick run the build_cmd, which
        // produces a fresh DLL; the source-dirty poll then triggers
        // project_loader.reload() automatically.
        if (state.abi_mismatch_open) {
            if (!ImGui::IsPopupOpen("ABI Mismatch")) {
                ImGui::OpenPopup("ABI Mismatch");
            }
            const ImGuiViewport* vp2 = ImGui::GetMainViewport();
            ImGui::SetNextWindowPos(
                ImVec2(vp2->WorkPos.x + vp2->WorkSize.x * 0.5f,
                       vp2->WorkPos.y + vp2->WorkSize.y * 0.5f),
                ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
            ImGui::SetNextWindowSize(ImVec2(460, 0), ImGuiCond_Appearing);
            if (ImGui::BeginPopupModal("ABI Mismatch", nullptr,
                    ImGuiWindowFlags_NoSavedSettings |
                    ImGuiWindowFlags_AlwaysAutoResize)) {
                ImGui::TextWrapped(
                    "Your project DLL was built against an older engine "
                    "API. The world autoload was skipped to protect your "
                    "saved data.");
                ImGui::Spacing();
                ImGui::Text("Project API: %u   Engine API: %u",
                            (unsigned)state.abi_mismatch_observed,
                            (unsigned)state.abi_mismatch_expected);
                ImGui::Spacing();
                ImGui::TextDisabled(
                    "Rebuild will compile your Lync sources, produce a "
                    "fresh project DLL, and reload it automatically. The "
                    "world autoload will then re-run.");
                ImGui::Separator();

                const bool can_rebuild = state.lync_watch.active();
                ImGui::BeginDisabled(!can_rebuild);
                if (ImGui::Button("Rebuild now", ImVec2(140, 0))) {
                    state.lync_watch.force_fire = true;
                    state.abi_mismatch_open = false;
                    editor::show_toast(state,
                        "Compiling project... will reload when ready.",
                        4.0f, false);
                    ImGui::CloseCurrentPopup();
                }
                ImGui::EndDisabled();
                if (!can_rebuild && ImGui::IsItemHovered()) {
                    ImGui::SetTooltip(
                        "Lync compiler isn't configured for this project.\n"
                        "Build the project DLL manually and reopen.");
                }
                ImGui::SameLine();
                if (ImGui::Button("Skip", ImVec2(100, 0))) {
                    state.abi_mismatch_open = false;
                    state.abi_pending_world_autoload.clear();
                    editor::show_toast(state,
                        "Project DLL not loaded. Rebuild manually + Ctrl+R.",
                        5.0f, true);
                    ImGui::CloseCurrentPopup();
                }
                ImGui::EndPopup();
            }
        }

        // ---- ABI mismatch: post-reload world autoload retry --------
        // Once the watcher has rebuilt + reloaded the project DLL, the
        // world we deliberately skipped at boot needs to be loaded so
        // the editor reaches the same state as a fresh open. Fires once
        // after the DLL becomes loaded and the path is still pending.
        if (!state.abi_pending_world_autoload.empty() &&
            project_loader.is_loaded()) {
            const std::string p = state.abi_pending_world_autoload;
            state.abi_pending_world_autoload.clear();
            state.world_save_locked = false;
            state.want_load_world_path = p;     // existing load-on-next-frame path
            editor::show_toast(state,
                "Project DLL rebuilt. Loading world.", 3.0f, false);
        }

        // Persist project_settings panel changes to .zuesproject.
        if (has_project && state.project_settings_dirty) {
            project.default_world          = state.project_default_world;
            project.settings.window_width  = state.project_window_width;
            project.settings.window_height = state.project_window_height;
            project.settings.fixed_size    = state.project_fixed_size;
            project.settings.fullscreen    = state.project_fullscreen;
            const auto proj_file = std::filesystem::path(project.project_dir)
                / (project.name + ".zuesproject");
            Engine::save_project(Engine::editor::path_str(proj_file).c_str(), project);
            state.project_settings_dirty = false;
        }
        editor::draw_toast_overlay(state);
        if (state.show_demo) ImGui::ShowDemoWindow(&state.show_demo);
        editor::imgui_end_frame();

        if (renderer) renderer->end_frame(renderer);
        window->swap_buffers(window);
        ++frames;
        ++state.editor_frame;
    }

    // Project on_unload + FreeLibrary BEFORE we tear down anything project
    // code might have observed (services, world, renderer state). The
    // unloader pulls project-registered systems out of the world first so
    // no dangling fn pointers can fire.
    project_loader.unload();
    host::set_host_context(nullptr);

    // Clean up RTs + demo texture + icons before shutting renderer down.
    if (renderer) {
        if (state.scene_rt     != 0) renderer->destroy_render_target(renderer, state.scene_rt);
        if (state.game_rt      != 0) renderer->destroy_render_target(renderer, state.game_rt);
        if (state.demo_texture != 0) renderer->free_texture(renderer, state.demo_texture);
        editor::icons_free(state.icons, renderer);
    }

    ZUES_LOG_INFO("editor loop exited - shutting down");
    editor::uninstall_log_sink();
    editor::imgui_shutdown();
    engine_shutdown();
    return 0;
}
