// --- MyGameProject ---
// Can be built as standalone EXE or as DLL for editor hot-reload
// Generated by ZuesEngine Editor

#include <filesystem>
#include <iostream>

#include "Engine.h"
#include "GameDLLInterface.h"
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include "ECS/World.h"
#include "Input.h"
#include "Renderer.h"

// ============================================================================
// YOUR GAME CODE - Add your custom components and systems here
// ============================================================================

// Example custom component (uncomment and modify):
// namespace Game {
//     struct PlayerComponent {
//         float health = 100.0f;
//         float speed = 5.0f;
//         int score = 0;
//     };
// }

// Example custom system (uncomment and modify):
// class PlayerMovementSystem : public SystemBase<
//     Engine::ECS::Component::TransformComponent*,
//     Game::PlayerComponent*
// > {
// public:
//     PlayerMovementSystem() { role = SystemRole::Game; }
//
//     void Update(float deltaTime,
//                 Engine::ECS::Component::TransformComponent* transform,
//                 Game::PlayerComponent* player) override {
//         // Your movement logic here
//         if (Engine::Input::IsKeyPressed(GLFW_KEY_W)) {
//             transform->worldPosition.y += player->speed * deltaTime;
//         }
//     }
// };

// ============================================================================
// GAME DLL EXPORTS (for editor hot-reload)
// ============================================================================
#ifdef GAME_DLL_EXPORTS

GAME_API_C int GameDLL_GetVersion() {
    return GAME_DLL_INTERFACE_VERSION;
}

GAME_API_C void GameDLL_Init(World* world) {
    std::cout << "[MyGameProject] Game initialized\n";
    // Called when the DLL is loaded in the editor
    // Add any initialization code here
}

GAME_API_C void GameDLL_Update(float deltaTime) {
    // Called every frame during play mode
    // Add custom per-frame logic here (outside of ECS systems)
}

GAME_API_C void GameDLL_Shutdown() {
    std::cout << "[MyGameProject] Game shutdown\n";
    // Called when the DLL is about to be unloaded
    // Clean up any resources here
}

GAME_API_C void GameDLL_RegisterComponents() {
    std::cout << "[MyGameProject] Registering components\n";
    // Register your custom components here:
    // Engine::ECS::Component::RegisterComponent<Game::PlayerComponent>();
}

GAME_API_C void GameDLL_RegisterSystems(World* world) {
    std::cout << "[MyGameProject] Registering systems\n";
    // Register your custom systems here:
    // world->RegisterSystem(std::make_unique<PlayerMovementSystem>());
}

// Optional: State preservation for hot-reload
GAME_API_C void* GameDLL_OnBeforeReload(size_t* outSize) {
    // Save any game state that needs to persist across reload
    // Return nullptr if no state needs to be saved
    *outSize = 0;
    return nullptr;
}

GAME_API_C void GameDLL_OnAfterReload(void* data, size_t size) {
    // Restore game state after reload
    // data will be the pointer returned from OnBeforeReload
}

#endif // GAME_DLL_EXPORTS

// ============================================================================
// STANDALONE EXECUTABLE (for final game builds)
// ============================================================================
#ifndef GAME_DLL_EXPORTS

GLFWwindow* g_MainWindow = nullptr;

int main() {
    if (!glfwInit()) {
        std::cerr << "FATAL: GLFW failed to initialize.\n";
        return -1;
    }

    glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE);
    GLFWwindow* window = glfwCreateWindow(1280, 720, "MyGameProject", nullptr, nullptr);
    if (!window) {
        std::cerr << "FATAL: GLFW failed to create window.\n";
        glfwTerminate();
        return -1;
    }

    g_MainWindow = window;
    glfwMakeContextCurrent(window);
    glfwSwapInterval(1);

    if (!gladLoadGLLoader(reinterpret_cast<GLADloadproc>(glfwGetProcAddress))) {
        std::cerr << "FATAL: Failed to initialize GLAD.\n";
        return -1;
    }

    Engine::Initialize(false, true, "0.0.0.0", 7777);

    const uint32_t GAME_FBO_ID = 1;
    int display_w = 1280, display_h = 720;

    while (!glfwWindowShouldClose(window)) {
        glfwPollEvents();
        Engine::Input::UpdateState();

        glfwGetFramebufferSize(window, &display_w, &display_h);
        Engine::Renderer::SetViewportSize(static_cast<float>(display_w), static_cast<float>(display_h));

        Engine::Renderer::Render();
        Engine::Update(System::SystemRole::Game);
        Engine::Renderer::EndBatch();

        glBindFramebuffer(GL_FRAMEBUFFER, 0);
        glViewport(0, 0, display_w, display_h);
        glClearColor(0.1f, 0.1f, 0.1f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

        glBindFramebuffer(GL_READ_FRAMEBUFFER, GAME_FBO_ID);
        glBindFramebuffer(GL_DRAW_FRAMEBUFFER, 0);
        glBlitFramebuffer(0, 0, display_w, display_h, 0, 0, display_w, display_h,
                          GL_COLOR_BUFFER_BIT, GL_NEAREST);

        glBindFramebuffer(GL_FRAMEBUFFER, 0);
        glfwSwapBuffers(window);
    }

    Engine::Shutdown();
    glfwDestroyWindow(window);
    glfwTerminate();

    return 0;
}

#endif // !GAME_DLL_EXPORTS
